# phpmyadmin
version: '3.1'

services:
  #db:
  #  image: mariadb:10.3
  #  restart: always
  #  environment:
  #    MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 7010:80
    environment:
      - PMA_ARBITRARY=1
      - TZ=Europe/Lisbon
