version: '3.7'

services:
  double-take:
    container_name: double-take
    image: jakowenko/double-take
    restart: unless-stopped
    volumes:
      - ~/docker-config/double-take/data:/.storage
    ports:
      - 5020:3000
    environment:
      - TZ=Europe/Lisbon
