version: "3.9"
services:
  docker_mon:
    image: philhawthorne/ha-dockermon
    container_name: ha_dockermon
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/docker-config/hadockerman/config:/config
    ports:
      - 8126:8126
    environment:
      - TZ=Europe/Lisbon
