version: "3.9"
services:
  deepstack:
    container_name: deepstack
    restart: unless-stopped
    image: deepquestai/deepstack
    ports:
      - '5000:5000'
    environment:
      - VISION-FACE=True
      - TZ=Europe/Lisbon
    volumes:
      - ./data:/datastore
      - ./data/pytorch-models:/modelstore/detection
