services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    environment:
      - TZ=Europe/Lisbon
    network_mode: host
    volumes:
      - /root/docker-config/mqttbroker/mosquitto/config/:/mosquitto/config/:ro
      - /root/docker-config/mqttbroker/mosquitto/data/:/mosquitto/data/
      - /root/docker-config/mqttbroker/mosquitto/log/:/mosquitto/log/
    ports:
      - 1883:1883
      - 9001:9001
    user: 1883:1883
